2023-04-22 16:19:37 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-22 16:19:37 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-22 16:19:45 INFO: Starting Windows assistant
2023-04-22 16:19:48 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-22 16:19:48 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-22 16:19:48 INFO: User said: who I am
2023-04-22 16:19:50 INFO: Starting Windows assistant
2023-04-22 16:19:53 WARNING: Error recognizing user input: 
2023-04-22 16:19:53 INFO: Starting Windows assistant
2023-04-22 16:19:58 WARNING: Error recognizing user input: 
2023-04-22 16:19:58 INFO: Starting Windows assistant
2023-04-27 19:58:05 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-27 19:58:05 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-27 19:58:13 INFO: Daisy: 
2023-04-27 19:58:16 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-27 19:58:16 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-27 19:58:16 WARNING: Error recognizing user input: 
2023-04-27 19:58:16 INFO: Daisy: 
2023-04-28 10:06:19 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:06:19 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:06:27 INFO: Daisy: 
2023-04-28 10:06:31 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:06:31 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:06:34 WARNING: Error recognizing user input: 
2023-04-28 10:06:34 INFO: Daisy: 
2023-04-28 10:07:56 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:07:56 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:08:04 INFO: Daisy: 
2023-04-28 10:08:07 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:08:07 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:08:11 INFO: User said: search Wikipedia open my
2023-04-28 10:08:34 INFO: Daisy: 
2023-04-28 10:08:44 INFO: User said: Wikipedia open AI
2023-04-28 10:09:08 INFO: Daisy: 
2023-04-28 10:09:15 INFO: User said: ok play some song
2023-04-28 10:09:21 INFO: Daisy: 
2023-04-28 10:09:34 WARNING: Error recognizing user input: 
2023-04-28 10:09:34 INFO: Daisy: 
2023-04-28 10:09:50 WARNING: Error recognizing user input: 
2023-04-28 10:09:50 INFO: Daisy: 
2023-04-28 10:09:55 WARNING: Error recognizing user input: 
2023-04-28 10:09:55 INFO: Daisy: 
2023-04-28 10:09:59 WARNING: Error recognizing user input: 
2023-04-28 10:09:59 INFO: Daisy: 
2023-04-28 10:10:02 WARNING: Error recognizing user input: 
2023-04-28 10:10:02 INFO: Daisy: 
2023-04-28 10:10:08 INFO: User said: what is the time
2023-04-28 10:10:12 INFO: Daisy: 
2023-04-28 10:10:15 WARNING: Error recognizing user input: 
2023-04-28 10:10:15 INFO: Daisy: 
2023-04-28 10:10:18 WARNING: Error recognizing user input: 
2023-04-28 10:10:18 INFO: Daisy: 
2023-04-28 10:10:21 WARNING: Error recognizing user input: 
2023-04-28 10:10:21 INFO: Daisy: 
2023-04-28 10:10:24 WARNING: Error recognizing user input: 
2023-04-28 10:10:24 INFO: Daisy: 
2023-04-28 10:10:37 WARNING: Error recognizing user input: 
2023-04-28 10:10:37 INFO: Daisy: 
2023-04-28 10:10:41 INFO: User said: open Wi-Fi
2023-04-28 10:10:44 INFO: Daisy: 
2023-04-28 10:10:47 WARNING: Error recognizing user input: 
2023-04-28 10:10:47 INFO: Daisy: 
2023-04-28 10:11:30 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:11:30 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:11:38 INFO: Daisy: 
2023-04-28 10:11:42 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:11:42 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:11:43 INFO: User said: open Firefox
2023-04-28 10:11:48 INFO: Daisy: 
2023-04-28 10:11:52 WARNING: Error recognizing user input: 
2023-04-28 10:11:52 INFO: Daisy: 
2023-04-28 10:11:57 INFO: User said: open Chrome
2023-04-28 10:12:02 INFO: Daisy: 
2023-04-28 10:12:09 INFO: User said: open edge
2023-04-28 10:12:09 INFO: Daisy: 
2023-04-28 10:12:11 WARNING: Error recognizing user input: 
2023-04-28 10:12:11 INFO: Daisy: 
2023-04-28 10:12:17 WARNING: Error recognizing user input: 
2023-04-28 10:12:17 INFO: Daisy: 
2023-04-28 10:12:23 INFO: User said: open Brave
2023-04-28 10:12:26 INFO: Daisy: 
2023-04-28 10:12:29 WARNING: Error recognizing user input: 
2023-04-28 10:12:29 INFO: Daisy: 
2023-04-28 10:12:38 WARNING: Error recognizing user input: 
2023-04-28 10:12:38 INFO: Daisy: 
2023-04-28 10:12:43 WARNING: Error recognizing user input: 
2023-04-28 10:12:43 INFO: Daisy: 
2023-04-28 10:12:48 WARNING: Error recognizing user input: 
2023-04-28 10:12:48 INFO: Daisy: 
2023-04-28 10:12:54 WARNING: Error recognizing user input: 
2023-04-28 10:12:54 INFO: Daisy: 
2023-04-28 10:12:59 INFO: User said: where is Kathmandu
2023-04-28 10:13:01 INFO: Daisy: 
2023-04-28 10:13:10 WARNING: Error recognizing user input: 
2023-04-28 10:13:10 INFO: Daisy: 
2023-04-28 10:13:13 WARNING: Error recognizing user input: 
2023-04-28 10:13:13 INFO: Daisy: 
2023-04-28 10:13:17 WARNING: Error recognizing user input: 
2023-04-28 10:13:17 INFO: Daisy: 
2023-04-28 10:13:27 WARNING: Error recognizing user input: 
2023-04-28 10:13:27 INFO: Daisy: 
2023-04-28 10:13:37 WARNING: Error recognizing user input: 
2023-04-28 10:13:37 INFO: Daisy: 
2023-04-28 10:13:42 WARNING: Error recognizing user input: 
2023-04-28 10:13:42 INFO: Daisy: 
2023-04-28 10:13:49 WARNING: Error recognizing user input: 
2023-04-28 10:13:49 INFO: Daisy: 
2023-04-28 10:13:54 WARNING: Error recognizing user input: 
2023-04-28 10:13:54 INFO: Daisy: 
2023-04-28 10:14:02 INFO: User said: weather information
2023-04-28 10:14:10 INFO: User said: Dehradun
2023-04-28 10:14:30 INFO: Daisy: 
2023-04-28 10:14:34 WARNING: Error recognizing user input: 
2023-04-28 10:14:34 INFO: Daisy: 
2023-04-28 10:14:38 WARNING: Error recognizing user input: 
2023-04-28 10:14:38 INFO: Daisy: 
2023-04-28 10:14:46 INFO: User said: weather forecast in Delhi
2023-04-28 10:14:52 INFO: Daisy: 
2023-04-28 10:14:57 WARNING: Error recognizing user input: 
2023-04-28 10:14:57 INFO: Daisy: 
2023-04-28 10:15:01 WARNING: Error recognizing user input: 
2023-04-28 10:15:01 INFO: Daisy: 
2023-04-28 10:15:06 WARNING: Error recognizing user input: 
2023-04-28 10:15:06 INFO: Daisy: 
2023-04-28 10:15:10 WARNING: Error recognizing user input: 
2023-04-28 10:15:10 INFO: Daisy: 
2023-04-28 10:15:15 WARNING: Error recognizing user input: 
2023-04-28 10:15:15 INFO: Daisy: 
2023-04-28 10:15:21 WARNING: Error recognizing user input: 
2023-04-28 10:15:21 INFO: Daisy: 
2023-04-28 10:15:29 WARNING: Error recognizing user input: 
2023-04-28 10:15:29 INFO: Daisy: 
2023-04-28 10:15:33 INFO: User said: tell me some today's news
2023-04-28 10:15:42 INFO: User said: India
2023-04-28 10:16:39 INFO: User said: health
2023-04-28 10:17:05 INFO: Daisy: 
2023-04-28 10:17:14 WARNING: Error recognizing user input: 
2023-04-28 10:17:14 INFO: Daisy: 
2023-04-28 10:17:22 WARNING: Error recognizing user input: 
2023-04-28 10:17:22 INFO: Daisy: 
2023-04-28 10:17:29 INFO: User said: tell me some today's stock price
2023-04-28 10:17:29 INFO: Daisy: 
2023-04-28 10:17:32 WARNING: Error recognizing user input: 
2023-04-28 10:17:32 INFO: Daisy: 
2023-04-28 10:17:47 INFO: User said: today stock price
2023-04-28 10:17:47 INFO: Daisy: 
2023-04-28 10:17:51 WARNING: Error recognizing user input: 
2023-04-28 10:17:51 INFO: Daisy: 
2023-04-28 10:17:54 WARNING: Error recognizing user input: 
2023-04-28 10:17:54 INFO: Daisy: 
2023-04-28 10:18:00 WARNING: Error recognizing user input: 
2023-04-28 10:18:00 INFO: Daisy: 
2023-04-28 10:18:07 INFO: User said: tell me today's stock price
2023-04-28 10:18:12 WARNING: Error recognizing user input: 
2023-04-28 10:18:14 INFO: Daisy: 
2023-04-28 10:18:25 WARNING: Error recognizing user input: 
2023-04-28 10:18:25 INFO: Daisy: 
2023-04-28 10:18:29 WARNING: Error recognizing user input: 
2023-04-28 10:18:29 INFO: Daisy: 
2023-04-28 10:18:33 WARNING: Error recognizing user input: 
2023-04-28 10:18:33 INFO: Daisy: 
2023-04-28 10:18:38 WARNING: Error recognizing user input: 
2023-04-28 10:18:38 INFO: Daisy: 
2023-04-28 10:18:42 WARNING: Error recognizing user input: 
2023-04-28 10:18:42 INFO: Daisy: 
2023-04-28 10:18:46 WARNING: Error recognizing user input: 
2023-04-28 10:18:46 INFO: Daisy: 
2023-04-28 10:18:52 WARNING: Error recognizing user input: 
2023-04-28 10:18:52 INFO: Daisy: 
2023-04-28 10:18:56 INFO: User said: what is your name
2023-04-28 10:19:01 INFO: Daisy: 
2023-04-28 10:19:04 WARNING: Error recognizing user input: 
2023-04-28 10:19:04 INFO: Daisy: 
2023-04-28 10:19:14 INFO: User said: who create you
2023-04-28 10:19:16 INFO: Daisy: 
2023-04-28 10:19:19 WARNING: Error recognizing user input: 
2023-04-28 10:19:19 INFO: Daisy: 
2023-04-28 10:19:29 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:19:29 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:19:37 INFO: Daisy: 
2023-04-28 10:19:40 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:19:40 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:19:43 INFO: User said: who create you
2023-04-28 10:19:45 INFO: Daisy: 
2023-04-28 10:19:50 WARNING: Error recognizing user input: 
2023-04-28 10:19:50 INFO: Daisy: 
2023-04-28 10:20:05 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:20:05 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:20:12 INFO: Daisy: 
2023-04-28 10:20:16 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:20:16 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:20:22 INFO: User said: Diu
2023-04-28 10:20:22 INFO: Daisy: 
2023-04-28 10:20:29 WARNING: Error recognizing user input: 
2023-04-28 10:20:29 INFO: Daisy: 
2023-04-28 10:20:37 INFO: User said: create u
2023-04-28 10:20:37 INFO: Daisy: 
2023-04-28 10:20:58 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:20:58 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:21:05 INFO: Daisy: 
2023-04-28 10:21:09 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:21:09 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:21:10 INFO: User said: tell me some jokes
2023-04-28 10:21:20 INFO: Daisy: 
2023-04-28 10:21:29 WARNING: Error recognizing user input: 
2023-04-28 10:21:29 INFO: Daisy: 
2023-04-28 10:21:36 INFO: User said: open Netflix
2023-04-28 10:21:38 INFO: Daisy: 
2023-04-28 10:21:45 WARNING: Error recognizing user input: 
2023-04-28 10:21:45 INFO: Daisy: 
2023-04-28 10:22:01 WARNING: Error recognizing user input: 
2023-04-28 10:22:01 INFO: Daisy: 
2023-04-28 10:22:07 WARNING: Error recognizing user input: 
2023-04-28 10:22:07 INFO: Daisy: 
2023-04-28 10:22:20 INFO: User said: open PowerPoint
2023-04-28 10:22:23 INFO: Daisy: 
2023-04-28 10:22:39 INFO: User said: present Sahab
2023-04-28 10:22:41 INFO: Daisy: 
2023-04-28 10:22:47 WARNING: Error recognizing user input: 
2023-04-28 10:22:47 INFO: Daisy: 
2023-04-28 10:23:04 WARNING: Error recognizing user input: 
2023-04-28 10:23:04 INFO: Daisy: 
2023-04-28 10:23:13 WARNING: Error recognizing user input: 
2023-04-28 10:23:13 INFO: Daisy: 
2023-04-28 10:23:20 WARNING: Error recognizing user input: 
2023-04-28 10:23:20 INFO: Daisy: 
2023-04-28 10:23:47 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:23:47 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:23:55 INFO: Daisy: 
2023-04-28 10:23:58 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:23:58 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:24:08 INFO: User said: what is the value of cos 30
2023-04-28 10:24:58 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:24:58 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:25:06 INFO: Daisy: 
2023-04-28 10:25:09 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:25:09 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:25:12 INFO: User said: what is the value of cos 30
2023-04-28 10:25:34 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:25:34 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:25:42 INFO: Daisy: 
2023-04-28 10:25:46 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:25:46 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:25:48 INFO: User said: what is value of cos 30
2023-04-28 10:28:08 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:28:08 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:28:16 INFO: Daisy: 
2023-04-28 10:28:20 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:28:20 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:28:20 INFO: User said: cos 30
2023-04-28 10:28:20 INFO: Daisy: 
2023-04-28 10:28:22 WARNING: Error recognizing user input: 
2023-04-28 10:28:22 INFO: Daisy: 
2023-04-28 10:28:35 INFO: User said: what is the value of cos 30
2023-04-28 10:30:36 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:30:36 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:30:44 INFO: Daisy: 
2023-04-28 10:30:53 INFO: User said: the value of cos 30
2023-04-28 10:30:53 INFO: Daisy: 
2023-04-28 10:30:53 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:30:53 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:31:00 WARNING: Error recognizing user input: 
2023-04-28 10:31:00 INFO: Daisy: 
2023-04-28 10:31:02 WARNING: Error recognizing user input: 
2023-04-28 10:31:02 INFO: Daisy: 
2023-04-28 10:31:11 INFO: User said: what is the value of cos 30
2023-04-28 10:35:15 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:35:15 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:35:23 INFO: Daisy: 
2023-04-28 10:35:26 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:35:26 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:35:27 INFO: User said: sin 30
2023-04-28 10:35:27 INFO: Daisy: 
2023-04-28 10:35:46 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:35:46 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:35:53 INFO: Daisy: 
2023-04-28 10:35:57 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:35:57 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:36:02 INFO: User said: what is the value of sin 30
2023-04-28 10:36:07 INFO: Daisy: 
2023-04-28 10:36:12 WARNING: Error recognizing user input: 
2023-04-28 10:36:12 INFO: Daisy: 
2023-04-28 10:36:21 INFO: User said: what is the value of cos sin 30
2023-04-28 10:36:45 INFO: Daisy: 
2023-04-28 10:37:03 INFO: User said: what is the value of Pi
2023-04-28 10:37:25 INFO: Daisy: 
2023-04-28 10:37:36 WARNING: Error recognizing user input: 
2023-04-28 10:37:36 INFO: Daisy: 
2023-04-28 10:37:50 WARNING: Error recognizing user input: 
2023-04-28 10:37:50 INFO: Daisy: 
2023-04-28 10:37:55 WARNING: Error recognizing user input: 
2023-04-28 10:37:55 INFO: Daisy: 
2023-04-28 10:38:07 WARNING: Error recognizing user input: 
2023-04-28 10:38:07 INFO: Daisy: 
2023-04-28 10:38:13 INFO: User said: difference between and gate and OR gate
2023-04-28 10:38:16 INFO: Daisy: 
2023-04-28 10:38:24 WARNING: Error recognizing user input: 
2023-04-28 10:38:24 INFO: Daisy: 
2023-04-28 10:38:29 WARNING: Error recognizing user input: 
2023-04-28 10:38:29 INFO: Daisy: 
2023-04-28 10:38:42 WARNING: Error recognizing user input: 
2023-04-28 10:38:42 INFO: Daisy: 
2023-04-28 10:38:55 INFO: User said: send SMS
2023-04-28 10:39:11 INFO: User said: 8650 1257 49
2023-04-28 10:39:18 INFO: User said: hello this is beta testing
2023-04-28 10:41:18 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:41:18 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:41:25 INFO: Daisy: 
2023-04-28 10:41:29 INFO: User said: send SMS
2023-04-28 10:41:29 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 10:41:29 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 10:41:41 INFO: User said: 8650 1257 49
2023-04-28 10:41:49 INFO: User said: hello this is beta testing
2023-04-28 12:07:51 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:07:51 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:07:59 INFO: Daisy: 
2023-04-28 12:08:02 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:08:02 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:08:03 INFO: User said: send SMS
2023-04-28 12:08:15 INFO: User said: 8650 1257 49
2023-04-28 12:08:22 INFO: User said: hello this is beta testing
2023-04-28 12:09:26 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:09:26 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:09:34 INFO: Daisy: 
2023-04-28 12:09:37 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:09:37 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:09:38 WARNING: Error recognizing user input: 
2023-04-28 12:09:38 INFO: Daisy: 
2023-04-28 12:09:43 INFO: User said: send SMS
2023-04-28 12:09:54 INFO: User said: 8650 1257 49
2023-04-28 12:10:00 INFO: User said: hello this is beta testing
2023-04-28 12:12:56 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:12:56 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:13:04 INFO: Daisy: 
2023-04-28 12:13:08 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:13:08 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:13:08 INFO: User said: send SMS
2023-04-28 12:13:19 INFO: User said: 8650 1257 49
2023-04-28 12:13:25 INFO: User said: hello
2023-04-28 12:23:35 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:23:35 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:23:43 INFO: Daisy: 
2023-04-28 12:23:48 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:23:48 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:23:48 INFO: User said: send SMS
2023-04-28 12:24:01 INFO: User said: 8650 185 749
2023-04-28 12:24:12 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:24:12 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:24:20 INFO: Daisy: 
2023-04-28 12:24:24 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:24:24 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\comtypes\gen'
2023-04-28 12:24:25 INFO: User said: send SMS
2023-04-28 12:24:39 INFO: User said: 8650 1257 49
2023-04-28 12:24:46 INFO: User said: hello
2023-04-28 12:50:13 INFO: Could not import comtypes.gen, trying to create it.
2023-04-28 12:50:13 INFO: Created comtypes.gen directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-28 12:50:13 INFO: Writing __init__.py file: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen\__init__.py'
2023-04-28 12:50:13 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-28 12:50:13 INFO: Could not import comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4: No module named 'comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4'
2023-04-28 12:50:13 INFO: # Generating comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4
2023-04-28 12:50:13 INFO: Could not import comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0: No module named 'comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0'
2023-04-28 12:50:13 INFO: # Generating comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0
2023-04-28 12:50:13 INFO: Could not import comtypes.gen.stdole: No module named 'comtypes.gen.stdole'
2023-04-28 12:50:13 INFO: # Generating comtypes.gen.stdole
2023-04-28 12:50:14 INFO: Could not import comtypes.gen.SpeechLib: No module named 'comtypes.gen.SpeechLib'
2023-04-28 12:50:14 INFO: # Generating comtypes.gen.SpeechLib
2023-04-28 12:50:22 INFO: Daisy: 
2023-04-28 12:50:29 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-28 12:50:29 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-28 12:50:30 INFO: User said: send SMS
2023-04-28 12:50:56 INFO: User said: 8650 1257 49
2023-04-28 12:51:07 INFO: User said: hello
2023-04-28 12:51:07 INFO: -- BEGIN Twilio API Request --
2023-04-28 12:51:07 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACfe6dfa49de5ba4307686b54dbed70b75/Messages.json
2023-04-28 12:51:07 INFO: Headers:
2023-04-28 12:51:07 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-28 12:51:07 INFO: X-Twilio-Client : python-8.1.0
2023-04-28 12:51:07 INFO: Accept-Charset : utf-8
2023-04-28 12:51:07 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-28 12:51:07 INFO: Accept : application/json
2023-04-28 12:51:07 INFO: -- END Twilio API Request --
2023-04-28 12:51:14 INFO: Response Status Code: 201
2023-04-28 12:51:14 INFO: Response Headers: {'Date': 'Fri, 28 Apr 2023 07:21:15 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQfba5735ce04b5c800b12b338e536de68', 'Twilio-Request-Duration': '0.135', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-28 12:51:14 INFO: Daisy: 
2023-04-29 10:56:42 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 10:56:42 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 10:56:50 INFO: Daisy: 
2023-04-29 10:57:03 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 10:57:03 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 10:57:36 INFO: User said: send SMS send SMS
2023-04-29 10:57:57 WARNING: Error recognizing user input: 
2023-04-29 10:59:24 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 10:59:24 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 10:59:31 INFO: Daisy: 
2023-04-29 10:59:37 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 10:59:37 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 10:59:48 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 10:59:48 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 10:59:56 INFO: Daisy: 
2023-04-29 10:59:59 WARNING: Error recognizing user input: 
2023-04-29 10:59:59 INFO: Daisy: 
2023-04-29 11:00:01 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:00:01 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:00:08 WARNING: Error recognizing user input: 
2023-04-29 11:00:08 INFO: Daisy: 
2023-04-29 11:00:13 INFO: User said: send SMS
2023-04-29 11:00:33 INFO: User said: 8650 1257 49
2023-04-29 11:01:06 INFO: User said: hello
2023-04-29 11:01:07 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:01:07 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACfe6dfa49de5ba4307686b54dbed70b75/Messages.json
2023-04-29 11:01:07 INFO: Headers:
2023-04-29 11:01:07 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:01:07 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:01:07 INFO: Accept-Charset : utf-8
2023-04-29 11:01:07 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:01:07 INFO: Accept : application/json
2023-04-29 11:01:07 INFO: -- END Twilio API Request --
2023-04-29 11:01:10 INFO: Response Status Code: 201
2023-04-29 11:01:10 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 05:31:11 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ0524948667c47bc13e7a1d3e09698ccb', 'Twilio-Request-Duration': '0.183', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:01:10 INFO: Daisy: 
2023-04-29 11:01:24 WARNING: Error recognizing user input: 
2023-04-29 11:01:24 INFO: Daisy: 
2023-04-29 11:01:30 WARNING: Error recognizing user input: 
2023-04-29 11:01:30 INFO: Daisy: 
2023-04-29 11:01:41 WARNING: Error recognizing user input: 
2023-04-29 11:01:41 INFO: Daisy: 
2023-04-29 11:02:45 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:02:45 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:02:52 INFO: Daisy: 
2023-04-29 11:02:56 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:02:56 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:02:57 INFO: User said: send SMS
2023-04-29 11:03:08 INFO: User said: 8650 1257 49
2023-04-29 11:03:14 INFO: User said: hello
2023-04-29 11:03:15 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:03:15 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACfe6dfa49de5ba4307686b54dbed70b75/Messages.json
2023-04-29 11:03:15 INFO: Headers:
2023-04-29 11:03:15 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:03:15 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:03:15 INFO: Accept-Charset : utf-8
2023-04-29 11:03:15 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:03:15 INFO: Accept : application/json
2023-04-29 11:03:15 INFO: -- END Twilio API Request --
2023-04-29 11:03:16 INFO: Response Status Code: 201
2023-04-29 11:03:16 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 05:33:18 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQbacf1faac0bd73c0f3a1014c840010cb', 'Twilio-Request-Duration': '0.141', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:03:16 INFO: Daisy: 
2023-04-29 11:03:21 WARNING: Error recognizing user input: 
2023-04-29 11:03:21 INFO: Daisy: 
2023-04-29 11:03:24 WARNING: Error recognizing user input: 
2023-04-29 11:03:24 INFO: Daisy: 
2023-04-29 11:03:27 WARNING: Error recognizing user input: 
2023-04-29 11:03:27 INFO: Daisy: 
2023-04-29 11:07:21 WARNING: Error recognizing user input: 
2023-04-29 11:07:21 INFO: Daisy: 
2023-04-29 11:07:26 WARNING: Error recognizing user input: 
2023-04-29 11:07:26 INFO: Daisy: 
2023-04-29 11:07:30 WARNING: Error recognizing user input: 
2023-04-29 11:07:30 INFO: Daisy: 
2023-04-29 11:07:40 WARNING: Error recognizing user input: 
2023-04-29 11:07:40 INFO: Daisy: 
2023-04-29 11:07:43 WARNING: Error recognizing user input: 
2023-04-29 11:07:43 INFO: Daisy: 
2023-04-29 11:07:46 WARNING: Error recognizing user input: 
2023-04-29 11:07:46 INFO: Daisy: 
2023-04-29 11:07:50 WARNING: Error recognizing user input: 
2023-04-29 11:07:50 INFO: Daisy: 
2023-04-29 11:07:53 WARNING: Error recognizing user input: 
2023-04-29 11:07:53 INFO: Daisy: 
2023-04-29 11:08:03 WARNING: Error recognizing user input: 
2023-04-29 11:08:03 INFO: Daisy: 
2023-04-29 11:08:06 WARNING: Error recognizing user input: 
2023-04-29 11:08:06 INFO: Daisy: 
2023-04-29 11:08:12 WARNING: Error recognizing user input: 
2023-04-29 11:08:12 INFO: Daisy: 
2023-04-29 11:08:20 WARNING: Error recognizing user input: 
2023-04-29 11:08:20 INFO: Daisy: 
2023-04-29 11:08:25 WARNING: Error recognizing user input: 
2023-04-29 11:08:25 INFO: Daisy: 
2023-04-29 11:08:29 WARNING: Error recognizing user input: 
2023-04-29 11:08:29 INFO: Daisy: 
2023-04-29 11:08:32 WARNING: Error recognizing user input: 
2023-04-29 11:08:32 INFO: Daisy: 
2023-04-29 11:18:34 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:18:34 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:18:41 INFO: Daisy: 
2023-04-29 11:18:45 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:18:45 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:18:46 INFO: User said: send SMS
2023-04-29 11:18:58 INFO: User said: 8650 1257 49
2023-04-29 11:19:04 INFO: User said: hello
2023-04-29 11:19:05 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:19:05 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:19:05 INFO: Headers:
2023-04-29 11:19:05 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:19:05 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:19:05 INFO: Accept-Charset : utf-8
2023-04-29 11:19:05 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:19:05 INFO: Accept : application/json
2023-04-29 11:19:05 INFO: -- END Twilio API Request --
2023-04-29 11:19:07 INFO: Response Status Code: 201
2023-04-29 11:19:07 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 05:49:08 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ1973967f273a456c3bbead71d5ce8043', 'Twilio-Request-Duration': '0.154', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:19:07 INFO: Daisy: 
2023-04-29 11:19:10 WARNING: Error recognizing user input: 
2023-04-29 11:19:10 INFO: Daisy: 
2023-04-29 11:19:17 WARNING: Error recognizing user input: 
2023-04-29 11:19:17 INFO: Daisy: 
2023-04-29 11:19:23 WARNING: Error recognizing user input: 
2023-04-29 11:19:23 INFO: Daisy: 
2023-04-29 11:19:29 WARNING: Error recognizing user input: 
2023-04-29 11:19:29 INFO: Daisy: 
2023-04-29 11:19:37 WARNING: Error recognizing user input: 
2023-04-29 11:19:37 INFO: Daisy: 
2023-04-29 11:19:48 WARNING: Error recognizing user input: 
2023-04-29 11:19:48 INFO: Daisy: 
2023-04-29 11:19:51 WARNING: Error recognizing user input: 
2023-04-29 11:19:51 INFO: Daisy: 
2023-04-29 11:19:53 WARNING: Error recognizing user input: 
2023-04-29 11:19:53 INFO: Daisy: 
2023-04-29 11:19:59 WARNING: Error recognizing user input: 
2023-04-29 11:19:59 INFO: Daisy: 
2023-04-29 11:20:02 WARNING: Error recognizing user input: 
2023-04-29 11:20:02 INFO: Daisy: 
2023-04-29 11:23:17 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:23:17 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:23:25 INFO: Daisy: 
2023-04-29 11:23:28 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:23:28 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:23:32 INFO: User said: send SMS
2023-04-29 11:23:34 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:23:34 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:23:34 INFO: Headers:
2023-04-29 11:23:34 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:23:34 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:23:34 INFO: Accept-Charset : utf-8
2023-04-29 11:23:34 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:23:34 INFO: Accept : application/json
2023-04-29 11:23:34 INFO: -- END Twilio API Request --
2023-04-29 11:23:36 INFO: Response Status Code: 201
2023-04-29 11:23:36 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 05:53:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQd03d0566bdc49ef6c4808ec9a7d7924e', 'Twilio-Request-Duration': '0.137', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:23:36 INFO: Daisy: 
2023-04-29 11:23:39 WARNING: Error recognizing user input: 
2023-04-29 11:23:39 INFO: Daisy: 
2023-04-29 11:23:44 WARNING: Error recognizing user input: 
2023-04-29 11:23:44 INFO: Daisy: 
2023-04-29 11:24:49 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:24:49 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:24:57 INFO: Daisy: 
2023-04-29 11:25:01 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:25:01 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:25:07 INFO: User said: send SMS
2023-04-29 11:25:09 INFO: Daisy: 
2023-04-29 11:25:14 WARNING: Error recognizing user input: 
2023-04-29 11:25:14 INFO: Daisy: 
2023-04-29 11:26:17 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:26:17 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:26:25 INFO: Daisy: 
2023-04-29 11:26:29 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:26:29 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:26:33 INFO: User said: send SMS
2023-04-29 11:26:45 INFO: User said: 8650 1257 49
2023-04-29 11:26:52 INFO: User said: hello
2023-04-29 11:26:52 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:26:52 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:26:52 INFO: Headers:
2023-04-29 11:26:52 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:26:52 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:26:52 INFO: Accept-Charset : utf-8
2023-04-29 11:26:52 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:26:52 INFO: Accept : application/json
2023-04-29 11:26:52 INFO: -- END Twilio API Request --
2023-04-29 11:26:55 INFO: Response Status Code: 201
2023-04-29 11:26:55 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 05:56:56 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQb0c5b401b9ba5b95315fa0f57840591d', 'Twilio-Request-Duration': '0.145', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:26:55 INFO: Daisy: 
2023-04-29 11:26:58 WARNING: Error recognizing user input: 
2023-04-29 11:26:58 INFO: Daisy: 
2023-04-29 11:27:04 WARNING: Error recognizing user input: 
2023-04-29 11:27:04 INFO: Daisy: 
2023-04-29 11:27:07 WARNING: Error recognizing user input: 
2023-04-29 11:27:07 INFO: Daisy: 
2023-04-29 11:28:12 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:28:12 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:28:19 INFO: Daisy: 
2023-04-29 11:28:23 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:28:23 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:28:24 INFO: User said: send an SMS
2023-04-29 11:28:26 INFO: Daisy: 
2023-04-29 11:28:33 WARNING: Error recognizing user input: 
2023-04-29 11:28:33 INFO: Daisy: 
2023-04-29 11:28:36 WARNING: Error recognizing user input: 
2023-04-29 11:28:36 INFO: Daisy: 
2023-04-29 11:28:53 WARNING: Error recognizing user input: 
2023-04-29 11:28:53 INFO: Daisy: 
2023-04-29 11:28:57 WARNING: Error recognizing user input: 
2023-04-29 11:28:57 INFO: Daisy: 
2023-04-29 11:29:44 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:29:44 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:29:51 INFO: Daisy: 
2023-04-29 11:29:55 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:29:55 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:29:56 INFO: User said: send SMS
2023-04-29 11:30:04 WARNING: Error recognizing user input: 
2023-04-29 11:30:10 INFO: User said: hello
2023-04-29 11:30:10 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:30:10 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:30:10 INFO: Headers:
2023-04-29 11:30:10 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:30:10 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:30:10 INFO: Accept-Charset : utf-8
2023-04-29 11:30:10 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:30:10 INFO: Accept : application/json
2023-04-29 11:30:10 INFO: -- END Twilio API Request --
2023-04-29 11:30:12 INFO: Response Status Code: 201
2023-04-29 11:30:12 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:00:14 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ3efa2dec5244dd8f6cbefcd26bf4e2a3', 'Twilio-Request-Duration': '0.132', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:30:12 INFO: Daisy: 
2023-04-29 11:30:19 WARNING: Error recognizing user input: 
2023-04-29 11:30:19 INFO: Daisy: 
2023-04-29 11:30:24 WARNING: Error recognizing user input: 
2023-04-29 11:30:24 INFO: Daisy: 
2023-04-29 11:30:28 WARNING: Error recognizing user input: 
2023-04-29 11:30:28 INFO: Daisy: 
2023-04-29 11:30:30 WARNING: Error recognizing user input: 
2023-04-29 11:30:30 INFO: Daisy: 
2023-04-29 11:30:40 WARNING: Error recognizing user input: 
2023-04-29 11:30:40 INFO: Daisy: 
2023-04-29 11:30:45 WARNING: Error recognizing user input: 
2023-04-29 11:30:45 INFO: Daisy: 
2023-04-29 11:30:48 WARNING: Error recognizing user input: 
2023-04-29 11:30:48 INFO: Daisy: 
2023-04-29 11:30:57 WARNING: Error recognizing user input: 
2023-04-29 11:30:57 INFO: Daisy: 
2023-04-29 11:31:02 WARNING: Error recognizing user input: 
2023-04-29 11:31:02 INFO: Daisy: 
2023-04-29 11:31:13 WARNING: Error recognizing user input: 
2023-04-29 11:31:13 INFO: Daisy: 
2023-04-29 11:31:18 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:31:18 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:31:25 INFO: Daisy: 
2023-04-29 11:31:33 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:31:33 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:31:33 INFO: User said: send SMS
2023-04-29 11:31:42 WARNING: Error recognizing user input: 
2023-04-29 11:31:56 WARNING: Error recognizing user input: 
2023-04-29 11:31:56 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:31:56 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:31:56 INFO: Headers:
2023-04-29 11:31:56 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:31:56 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:31:56 INFO: Accept-Charset : utf-8
2023-04-29 11:31:56 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:31:56 INFO: Accept : application/json
2023-04-29 11:31:56 INFO: -- END Twilio API Request --
2023-04-29 11:32:01 INFO: Response Status Code: 400
2023-04-29 11:32:01 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:02:03 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '150', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ41d581e2259005b2fec2128be864945e', 'Twilio-Request-Duration': '0.055', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:33:54 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:33:54 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:34:02 INFO: Daisy: 
2023-04-29 11:34:07 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:34:07 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:34:12 INFO: User said: send SMS
2023-04-29 11:34:25 INFO: User said: 8650 1257 49
2023-04-29 11:34:31 INFO: User said: hello
2023-04-29 11:34:32 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:34:32 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:34:32 INFO: Headers:
2023-04-29 11:34:32 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:34:32 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:34:32 INFO: Accept-Charset : utf-8
2023-04-29 11:34:32 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:34:32 INFO: Accept : application/json
2023-04-29 11:34:32 INFO: -- END Twilio API Request --
2023-04-29 11:34:34 INFO: Response Status Code: 201
2023-04-29 11:34:34 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:04:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQe7d5b5b342383f8a17df6275fe477e6e', 'Twilio-Request-Duration': '0.139', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 11:34:34 INFO: Daisy: 
2023-04-29 11:34:38 WARNING: Error recognizing user input: 
2023-04-29 11:34:38 INFO: Daisy: 
2023-04-29 11:34:43 WARNING: Error recognizing user input: 
2023-04-29 11:34:43 INFO: Daisy: 
2023-04-29 11:35:42 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:35:42 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:35:49 INFO: Daisy: 
2023-04-29 11:35:53 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:35:53 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:35:54 INFO: User said: send WhatsApp message
2023-04-29 11:36:05 WARNING: Error recognizing user input: 
2023-04-29 11:36:15 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:36:15 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:36:22 INFO: Daisy: 
2023-04-29 11:36:25 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:36:25 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:36:25 INFO: User said: WhatsApp message
2023-04-29 11:36:36 INFO: User said: 817 1169 299
2023-04-29 11:37:00 INFO: User said: hello hello
2023-04-29 11:37:18 INFO: Daisy: 
2023-04-29 11:37:21 WARNING: Error recognizing user input: 
2023-04-29 11:37:21 INFO: Daisy: 
2023-04-29 11:37:24 WARNING: Error recognizing user input: 
2023-04-29 11:37:24 INFO: Daisy: 
2023-04-29 11:37:27 WARNING: Error recognizing user input: 
2023-04-29 11:37:27 INFO: Daisy: 
2023-04-29 11:37:32 WARNING: Error recognizing user input: 
2023-04-29 11:37:32 INFO: Daisy: 
2023-04-29 11:37:38 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:37:38 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:37:45 INFO: Daisy: 
2023-04-29 11:37:49 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:37:49 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:38:03 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:38:03 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:38:10 INFO: Daisy: 
2023-04-29 11:38:13 INFO: User said: message
2023-04-29 11:38:13 INFO: Daisy: 
2023-04-29 11:38:14 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:38:14 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:38:16 WARNING: Error recognizing user input: 
2023-04-29 11:38:16 INFO: Daisy: 
2023-04-29 11:38:19 WARNING: Error recognizing user input: 
2023-04-29 11:38:19 INFO: Daisy: 
2023-04-29 11:38:24 WARNING: Error recognizing user input: 
2023-04-29 11:38:24 INFO: Daisy: 
2023-04-29 11:38:27 INFO: User said: message
2023-04-29 11:38:27 INFO: Daisy: 
2023-04-29 11:38:30 WARNING: Error recognizing user input: 
2023-04-29 11:38:30 INFO: Daisy: 
2023-04-29 11:38:35 WARNING: Error recognizing user input: 
2023-04-29 11:38:35 INFO: Daisy: 
2023-04-29 11:38:37 WARNING: Error recognizing user input: 
2023-04-29 11:38:37 INFO: Daisy: 
2023-04-29 11:38:41 INFO: User said: SAP message
2023-04-29 11:38:41 INFO: Daisy: 
2023-04-29 11:38:46 WARNING: Error recognizing user input: 
2023-04-29 11:38:46 INFO: Daisy: 
2023-04-29 11:38:49 WARNING: Error recognizing user input: 
2023-04-29 11:38:49 INFO: Daisy: 
2023-04-29 11:38:56 WARNING: Error recognizing user input: 
2023-04-29 11:38:56 INFO: Daisy: 
2023-04-29 11:39:06 INFO: User said: send WhatsApp message
2023-04-29 11:39:20 INFO: User said: 17 1169
2023-04-29 11:39:27 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:39:27 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:39:34 INFO: Daisy: 
2023-04-29 11:39:37 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:39:37 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:39:38 INFO: User said: message
2023-04-29 11:39:38 INFO: Daisy: 
2023-04-29 11:39:49 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:39:49 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:39:56 INFO: Daisy: 
2023-04-29 11:40:00 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:40:00 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:40:00 INFO: User said: message
2023-04-29 11:40:00 INFO: Daisy: 
2023-04-29 11:40:08 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:40:08 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:40:16 INFO: Daisy: 
2023-04-29 11:40:19 WARNING: Error recognizing user input: 
2023-04-29 11:40:19 INFO: Daisy: 
2023-04-29 11:40:19 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:40:19 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:57:53 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:57:53 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:58:15 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:58:15 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:58:22 INFO: Daisy: 
2023-04-29 11:58:26 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 11:58:26 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 11:58:27 INFO: User said: send SMS
2023-04-29 11:58:37 INFO: User said: 8650 185 749
2023-04-29 11:58:42 INFO: User said: hello
2023-04-29 11:58:42 INFO: -- BEGIN Twilio API Request --
2023-04-29 11:58:42 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 11:58:42 INFO: Headers:
2023-04-29 11:58:42 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 11:58:42 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 11:58:42 INFO: Accept-Charset : utf-8
2023-04-29 11:58:42 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 11:58:42 INFO: Accept : application/json
2023-04-29 11:58:42 INFO: -- END Twilio API Request --
2023-04-29 11:58:45 INFO: Response Status Code: 400
2023-04-29 11:58:45 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:28:46 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '314', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ869cad77e28416072fe4b754e3096c6e', 'Twilio-Request-Duration': '0.366', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 12:02:51 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:02:51 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:02:58 INFO: Daisy: 
2023-04-29 12:03:02 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:03:02 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:03:02 INFO: User said: send SMS
2023-04-29 12:03:17 WARNING: Error recognizing user input: 
2023-04-29 12:03:17 INFO: -- BEGIN Twilio API Request --
2023-04-29 12:03:17 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 12:03:17 INFO: Headers:
2023-04-29 12:03:17 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 12:03:17 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 12:03:17 INFO: Accept-Charset : utf-8
2023-04-29 12:03:17 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 12:03:17 INFO: Accept : application/json
2023-04-29 12:03:17 INFO: -- END Twilio API Request --
2023-04-29 12:03:20 INFO: Response Status Code: 201
2023-04-29 12:03:20 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:33:22 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '807', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQf777977a2536a10666c68be522ac3e5c', 'Twilio-Request-Duration': '0.132', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 12:03:20 INFO: Daisy: 
2023-04-29 12:03:24 WARNING: Error recognizing user input: 
2023-04-29 12:03:24 INFO: Daisy: 
2023-04-29 12:03:35 WARNING: Error recognizing user input: 
2023-04-29 12:03:35 INFO: Daisy: 
2023-04-29 12:03:55 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:03:55 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:04:03 INFO: Daisy: 
2023-04-29 12:04:07 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:04:07 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:04:07 INFO: User said: send SMS
2023-04-29 12:04:18 INFO: User said: 6501 25 749
2023-04-29 12:04:23 INFO: User said: hello this is beta testing
2023-04-29 12:04:24 INFO: -- BEGIN Twilio API Request --
2023-04-29 12:04:24 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 12:04:24 INFO: Headers:
2023-04-29 12:04:24 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 12:04:24 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 12:04:24 INFO: Accept-Charset : utf-8
2023-04-29 12:04:24 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 12:04:24 INFO: Accept : application/json
2023-04-29 12:04:24 INFO: -- END Twilio API Request --
2023-04-29 12:04:26 INFO: Response Status Code: 400
2023-04-29 12:04:26 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:34:28 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '159', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ8b1b8fc7a111ea84492d22ac40bd5b88', 'Twilio-Request-Duration': '0.064', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 12:05:34 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:05:34 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:05:42 INFO: Daisy: 
2023-04-29 12:05:46 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:05:46 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:05:47 INFO: User said: SMS
2023-04-29 12:05:55 INFO: User said: 8650 1257 49
2023-04-29 12:06:02 INFO: User said: hello
2023-04-29 12:06:03 INFO: -- BEGIN Twilio API Request --
2023-04-29 12:06:03 INFO: POST Request: https://api.twilio.com/2010-04-01/Accounts/ACca2a2e81f89cbf098d22d69f858edb36/Messages.json
2023-04-29 12:06:03 INFO: Headers:
2023-04-29 12:06:03 INFO: User-Agent : twilio-python/8.1.0 (Windows AMD64) Python/3.11.2
2023-04-29 12:06:03 INFO: X-Twilio-Client : python-8.1.0
2023-04-29 12:06:03 INFO: Accept-Charset : utf-8
2023-04-29 12:06:03 INFO: Content-Type : application/x-www-form-urlencoded
2023-04-29 12:06:03 INFO: Accept : application/json
2023-04-29 12:06:03 INFO: -- END Twilio API Request --
2023-04-29 12:06:05 INFO: Response Status Code: 201
2023-04-29 12:06:05 INFO: Response Headers: {'Date': 'Sat, 29 Apr 2023 06:36:07 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '808', 'Connection': 'keep-alive', 'Twilio-Request-Id': 'RQ353e495790f5c0db2abdf5d97e87b1d2', 'Twilio-Request-Duration': '0.125', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Idempotency-Key', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS', 'Access-Control-Expose-Headers': 'ETag', 'Access-Control-Allow-Credentials': 'true', 'X-Powered-By': 'AT-5000', 'Twilio-Concurrent-Requests': '1', 'X-Shenanigans': 'none', 'X-Home-Region': 'us1', 'X-API-Domain': 'api.twilio.com', 'Strict-Transport-Security': 'max-age=31536000'}
2023-04-29 12:06:05 INFO: Daisy: 
2023-04-29 12:06:15 WARNING: Error recognizing user input: 
2023-04-29 12:06:15 INFO: Daisy: 
2023-04-29 12:06:56 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:06:56 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:07:03 INFO: Daisy: 
2023-04-29 12:07:07 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:07:07 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:07:07 INFO: User said: send WhatsApp message
2023-04-29 12:07:14 WARNING: Error recognizing user input: 
2023-04-29 12:07:25 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:07:25 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:07:33 INFO: Daisy: 
2023-04-29 12:07:38 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:07:38 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:07:44 WARNING: Error recognizing user input: 
2023-04-29 12:07:44 INFO: Daisy: 
2023-04-29 12:07:49 INFO: User said: send WhatsApp message
2023-04-29 12:07:58 INFO: User said: 17116 9299
2023-04-29 12:08:06 INFO: User said: hello
2023-04-29 12:08:22 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:08:22 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:08:30 INFO: Daisy: 
2023-04-29 12:08:33 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:08:33 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:08:37 INFO: User said: send WhatsApp message
2023-04-29 12:08:48 INFO: User said: 817 1169 299
2023-04-29 12:08:58 INFO: User said: hello
2023-04-29 12:09:15 INFO: Daisy: 
2023-04-29 12:09:19 WARNING: Error recognizing user input: 
2023-04-29 12:09:19 INFO: Daisy: 
2023-04-29 12:09:36 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:09:36 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:09:44 INFO: Daisy: 
2023-04-29 12:09:47 WARNING: Error recognizing user input: 
2023-04-29 12:09:47 INFO: Daisy: 
2023-04-29 12:09:48 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:09:48 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:10:20 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:10:20 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:10:27 INFO: Daisy: 
2023-04-29 12:10:31 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:10:31 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:10:33 INFO: User said: send WhatsApp message
2023-04-29 12:10:43 INFO: User said: 817 1169 299
2023-04-29 12:11:44 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:11:44 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:11:52 INFO: Daisy: 
2023-04-29 12:11:56 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:11:56 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:11:59 WARNING: Error recognizing user input: 
2023-04-29 12:11:59 INFO: Daisy: 
2023-04-29 12:12:08 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:12:08 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:12:16 INFO: Daisy: 
2023-04-29 12:12:21 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 12:12:21 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 12:12:29 INFO: User said: send WhatsApp message
2023-04-29 12:12:48 INFO: User said: 817 1169 299
2023-04-29 12:12:55 WARNING: Error recognizing user input: 
2023-04-29 12:13:12 INFO: Daisy: 
2023-04-29 12:13:21 WARNING: Error recognizing user input: 
2023-04-29 12:13:21 INFO: Daisy: 
2023-04-29 12:13:24 WARNING: Error recognizing user input: 
2023-04-29 12:13:24 INFO: Daisy: 
2023-04-29 12:13:34 WARNING: Error recognizing user input: 
2023-04-29 12:13:34 INFO: Daisy: 
2023-04-29 12:13:37 WARNING: Error recognizing user input: 
2023-04-29 12:13:37 INFO: Daisy: 
2023-04-29 12:13:43 WARNING: Error recognizing user input: 
2023-04-29 12:13:43 INFO: Daisy: 
2023-04-29 12:13:49 WARNING: Error recognizing user input: 
2023-04-29 12:13:49 INFO: Daisy: 
2023-04-29 12:14:18 WARNING: Error recognizing user input: 
2023-04-29 12:14:18 INFO: Daisy: 
2023-04-29 12:14:26 WARNING: Error recognizing user input: 
2023-04-29 12:14:26 INFO: Daisy: 
2023-04-29 12:14:29 WARNING: Error recognizing user input: recognition connection failed: [Errno 11001] getaddrinfo failed
2023-04-29 12:14:29 INFO: Daisy: 
2023-04-29 20:39:06 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 20:39:06 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 20:39:13 INFO: Daisy: 
2023-04-29 20:39:15 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 20:39:15 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-04-29 20:40:48 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-04-29 20:40:48 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 13:59:10 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 13:59:10 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 13:59:11 INFO: Could not import comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4: Typelib different than module
2023-05-11 13:59:11 INFO: # Generating comtypes.gen._C866CA3A_32F7_11D2_9602_00C04F8EE628_0_5_4
2023-05-11 13:59:11 INFO: Could not import comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0: Typelib different than module
2023-05-11 13:59:11 INFO: # Generating comtypes.gen._00020430_0000_0000_C000_000000000046_0_2_0
2023-05-11 13:59:21 INFO: Daisy: 
2023-05-11 13:59:44 INFO: User said: hello Daisy how are you
2023-05-11 13:59:46 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 13:59:46 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 13:59:55 INFO: User said: it's vedansh
2023-05-11 13:59:58 INFO: Daisy: 
2023-05-11 14:00:03 INFO: User said: I am fine thank you
2023-05-11 14:00:06 INFO: Daisy: 
2023-05-11 14:00:09 WARNING: Error recognizing user input: 
2023-05-11 14:00:09 INFO: Daisy: 
2023-05-11 14:00:13 WARNING: Error recognizing user input: 
2023-05-11 14:00:13 INFO: Daisy: 
2023-05-11 14:00:32 WARNING: Error recognizing user input: 
2023-05-11 14:00:32 INFO: Daisy: 
2023-05-11 14:00:36 WARNING: Error recognizing user input: 
2023-05-11 14:00:36 INFO: Daisy: 
2023-05-11 14:00:39 WARNING: Error recognizing user input: 
2023-05-11 14:00:39 INFO: Daisy: 
2023-05-11 14:00:43 WARNING: Error recognizing user input: 
2023-05-11 14:00:43 INFO: Daisy: 
2023-05-11 14:00:46 WARNING: Error recognizing user input: 
2023-05-11 14:00:46 INFO: Daisy: 
2023-05-11 14:01:05 INFO: User said: application
2023-05-11 14:01:05 INFO: Daisy: 
2023-05-11 14:01:10 WARNING: Error recognizing user input: 
2023-05-11 14:01:10 INFO: Daisy: 
2023-05-11 14:01:13 WARNING: Error recognizing user input: 
2023-05-11 14:01:13 INFO: Daisy: 
2023-05-11 14:01:18 WARNING: Error recognizing user input: 
2023-05-11 14:01:18 INFO: Daisy: 
2023-05-11 14:01:21 WARNING: Error recognizing user input: 
2023-05-11 14:01:21 INFO: Daisy: 
2023-05-11 14:01:36 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 14:01:36 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 14:01:46 INFO: Daisy: 
2023-05-11 14:01:52 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 14:01:52 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 14:01:54 WARNING: Error recognizing user input: 
2023-05-11 14:01:54 INFO: Daisy: 
2023-05-11 14:01:59 WARNING: Error recognizing user input: 
2023-05-11 14:01:59 INFO: Daisy: 
2023-05-11 14:03:01 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 14:03:01 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 14:03:11 INFO: Daisy: 
2023-05-11 14:03:14 INFO: Imported existing <module 'comtypes.gen' from 'C:\\Users\\vedan\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\comtypes\\gen\\__init__.py'>
2023-05-11 14:03:14 INFO: Using writeable comtypes cache directory: 'C:\Users\vedan\AppData\Local\Programs\Python\Python311\Lib\site-packages\comtypes\gen'
2023-05-11 14:03:14 INFO: User said: open PowerPoint
2023-05-11 14:03:18 INFO: Daisy: 
2023-05-11 14:03:24 INFO: User said: close PowerPoint
2023-05-11 14:03:27 INFO: Daisy: 
2023-05-11 14:03:30 WARNING: Error recognizing user input: 
2023-05-11 14:03:30 INFO: Daisy: 
2023-05-11 14:03:39 WARNING: Error recognizing user input: 
2023-05-11 14:03:39 INFO: Daisy: 
